name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release latest"
    runs-on: "ubuntu-latest"
    steps:
      - name: install platform io
        run: 
          pip install -U platformio
          platformio update
      - name: "Build & test"
        env:
          PLATFORMIO_CI_SRC : examples/LedControllerDemoRocket/LedControllerDemoRocket.ino
        run: |
          platformio ci --lib="." --board=esp32dev

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            License
            library.properties
            keywords.txt